export const ADD_TODO_ITEM = "ADD_TODO_ITEM";
export const EDIT_TODO_ITEM = "EDIT_TODO_ITEM";
export const GET_TODO_ITEM = "GET_TODO_ITEM";
export const GET_DELETED_TODO_ITEM = "GET_DELETED_TODO_ITEM";
export const GET_COMPLETED_TODO_ITEM = "GET_COMPLETED_TODO_ITEM";